SEGMENTS = {
    "young_students": {
        "age_range": (18, 25),
        "marital_p":   {"single": 0.95, "married": 0.05},
        "education_p": {"university": 0.70, "highschool": 0.30},
        "employment_p": {"student": 0.60, "employed": 0.20, "part_time": 0.10, "unemployed": 0.10},
        "job_titles": ["University Student", "Intern", "Assistant", "Barista"],
        "housing_p": {"rent": 0.60, "family": 0.40},
        "month_factor_range": (0.7, 1.3),
        "credit_mu": 625, "credit_sigma": 30,
        "num_dep_range": (0, 1),
        "weekly_txn_rate": (10, 18),
        "channel_shares": {"POS": 0.70, "online": 0.28, "ATM": 0.015, "branch": 0.005},
        "tod_mean_std": (17.5, 4.0),
        "category_weights": {
            "gas": 0.1, "grocery": 0.4, "restaurant": 3, "shopping": 0.5,
            "healthcare": 0.1, "transportation": 0.15, "public_transportation": 0,
            "entertainment": 0.75, "ATM": 0.01
        },
    },
    "young_professionals": {
        "age_range": (23, 35),
        "marital_p":   {"single": 0.70, "married": 0.30},
        "education_p": {"bachelor": 0.60, "master": 0.20, "highschool": 0.20},
        "employment_p": {"employed": 1.0},
        "job_titles": ["Software Engineer", "Marketing Specialist", "Analyst", "Designer"],
        "housing_p": {"rent": 0.60, "own": 0.40},
        "month_factor_range": (1.5, 2.5),
        "credit_mu": 700, "credit_sigma": 35,
        "num_dep_range": (0, 1),
        "weekly_txn_rate": (10, 18),
        "channel_shares": {"POS": 0.65, "online": 0.30, "ATM": 0.03, "branch": 0.02},
        "tod_mean_std": (18.0, 3.5),
        "category_weights": {
            "gas": 0.5, "grocery": 1, "restaurant": 2.5, "shopping": 1.5,
            "healthcare": 0.04, "transportation": 0.1, "public_transportation": 0,
            "entertainment": 0.75, "ATM": 0.01
        },
    },
    "blue_collar": {
        "age_range": (18, 50),
        "marital_p":   {"single": 0.45, "married": 0.55},
        "education_p": {"primary": 0.25, "secondary": 0.45, "highschool": 0.30},
        "employment_p": {"employed": 1.0},
        "job_titles": ["Technician", "Driver", "Shopkeeper", "Operator"],
        "housing_p": {"rent": 0.50, "own": 0.20, "family": 0.30},
        "month_factor_range": (1.0, 2.0),
        "credit_mu": 655, "credit_sigma": 30,
        "num_dep_range": (0, 3),
        "weekly_txn_rate": (8, 14),
        "channel_shares": {"POS": 0.65, "online": 0.25, "ATM": 0.08, "branch": 0.02},
        "tod_mean_std": (17.5, 4.0),
        "category_weights": {
            "gas": 1.25, "grocery": 1, "restaurant": 1, "shopping": 0.75,
            "healthcare": 1, "transportation": 0.02, "public_transportation": 0,
            "entertainment": 0.04, "ATM": 1
        },
    },
    "mid_career_families": {
        "age_range": (30, 50),
        "marital_p":   {"married": 0.95, "single": 0.05},
        "education_p": {"bachelor": 0.50, "master": 0.35, "highschool": 0.15},
        "employment_p": {"employed": 1.0},
        "job_titles": ["Project Manager", "Accountant", "Sales Manager", "Teacher"],
        "housing_p": {"own": 0.90, "rent": 0.10},
        "month_factor_range": (2.0, 3.0),
        "credit_mu": 725, "credit_sigma": 30,
        "num_dep_range": (1, 3),
        "weekly_txn_rate": (12, 18),
        "channel_shares": {"POS": 0.60, "online": 0.30, "ATM": 0.08, "branch": 0.02},
        "tod_mean_std": (17.0, 4.0),
        "category_weights": {
            "gas": 2, "grocery": 1, "restaurant": 1, "shopping": 1.7,
            "healthcare": 0.5, "transportation": 0.03, "public_transportation": 0,
            "entertainment": 0.5, "ATM": 0.2
        },
    },
    "retirees": {
        "age_range": (55, 80),
        "marital_p":   {"married": 0.60, "widowed": 0.25, "single": 0.15},
        "education_p": {"highschool": 0.50, "secondary": 0.30, "bachelor": 0.20},
        "employment_p": {"retired": 1.0},
        "job_titles": ["Retired"],
        "housing_p": {"own": 0.80, "family": 0.20},
        "month_factor_range": (0.7, 1.5),  # actual pick uses RE flag below
        "credit_mu": 685, "credit_sigma": 30,
        "num_dep_range": (0, 2),
        "weekly_txn_rate": (4, 8),
        "channel_shares": {"POS": 0.45, "online": 0.35, "ATM": 0.18, "branch": 0.02},
        "tod_mean_std": (15.5, 4.5),
        "category_weights": {
            "gas": 1.5, "grocery": 1.25, "restaurant": 0.25, "shopping": 0.25,
            "healthcare": 0.2, "transportation": 0.01, "public_transportation": 0,
            "entertainment": 0.02, "ATM": 0.5
        },
    },
    "high_income": {
        "age_range": (35, 60),
        "marital_p":   {"married": 0.70, "single": 0.30},
        "education_p": {"master": 0.50, "phd": 0.20, "bachelor": 0.30},
        "employment_p": {"employed": 1.0},
        "job_titles": ["Senior Manager", "Director", "CTO", "CFO"],
        "housing_p": {"own": 0.95, "rent": 0.05},
        "month_factor_range": (4.0, 5.0),
        "credit_mu": 785, "credit_sigma": 30,
        "num_dep_range": (0, 3),
        "weekly_txn_rate": (15, 25),
        "channel_shares": {"POS": 0.40, "online": 0.50, "ATM": 0.05, "branch": 0.05},
        "tod_mean_std": (17.5, 3.5),
        "category_weights": {
            "gas": 1.5, "grocery": 1.5, "restaurant": 9, "shopping": 3,
            "healthcare": 0.1, "transportation": 0.2, "public_transportation": 0,
            "entertainment": 0.5, "ATM": 0.01
        },
    },
}